<script>
	import Card from '../components/Card.svelte';
	import { onMount } from 'svelte';

	onMount(() => {
		const options = {
			strings: ['Planning', 'Staffing', 'Management'],
			typeSpeed: 50,
			backSpeed: 50,
			smartBackSpace: true,
			loop: true
		};

		const typed = new Typed('#event-text', options);
	});
</script>

<svelte:head>
	<title>Home</title>
</svelte:head>

<div class="cover">
	<div data-aos="fade-right" class="text-box cover-item">
		<h1 class="cover-text">We'll Handle It</h1>
		<h2>Event <span id="event-text"></span></h2>
	</div>
	<div class="logo-img cover-item" />
	<a data-aos="fade-left" class="purchase-link cover-item" href="/pricing"> Purchase event staffing</a>
</div>

<section></section>

<style>
	.cover-text {
		color: white;
		text-align: center;
		font-size: 35px;
		margin-right: 7.5px;
	}

	.purchase-link {
		margin-left: 8px;
		border-radius: 10px;
		padding: 7px;
		color: gold;
		border: 2px solid white;
		transition: all 300ms ease-in-out;
	}

	.purchase-link:hover {
		transform: scale(1.05);
	}

	.cover-item {
		margin: 40px;
	}

	/* ----------------------------------------------
 * Generated by Animista on 2022-8-13 18:39:8
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

	/**
 * ----------------------------------------
 * animation swing-in-top-fwd
 * ----------------------------------------
 */
	@-webkit-keyframes swing-in-top-fwd {
		0% {
			-webkit-transform: rotateX(-100deg);
			transform: rotateX(-100deg);
			-webkit-transform-origin: top;
			transform-origin: top;
			opacity: 0;
		}
		100% {
			-webkit-transform: rotateX(0deg);
			transform: rotateX(0deg);
			-webkit-transform-origin: top;
			transform-origin: top;
			opacity: 1;
		}
	}
	@keyframes swing-in-top-fwd {
		0% {
			-webkit-transform: rotateX(-100deg);
			transform: rotateX(-100deg);
			-webkit-transform-origin: top;
			transform-origin: top;
			opacity: 0;
		}
		100% {
			-webkit-transform: rotateX(0deg);
			transform: rotateX(0deg);
			-webkit-transform-origin: top;
			transform-origin: top;
			opacity: 1;
		}
	}

	h2 {
		margin-left: 10.5px;
		color: white;
		font-weight: 100;
		font-size: 17px;
	}

	.cover {
		display: flex;
		align-items: center;
		justify-content: center;
		flex-wrap: wrap;
		margin-top: 50px;
		background-image: url('https://handlers.ca/wp-content/uploads/2022/06/Rose-Backg3.png');
		background-position: center center;
		background-size: cover;
		background-repeat: no-repeat;
	}

	.logo-img {
		background-image: url('https://handlers.ca/wp-content/uploads/2022/06/Black-Logo.png');
		background-position: center;
		background-size: contain;
		background-repeat: no-repeat;
		width: 200px;
		height: 200px;
        -webkit-animation: swing-in-top-fwd 1.5s cubic-bezier(0.175, 0.885, 0.320, 1.275) both;
	    animation: swing-in-top-fwd 1.5s cubic-bezier(0.175, 0.885, 0.320, 1.275) both;
	}
</style>
